alias matrule='git -c "user.name=Mat Rule (User Persona)" -c "user.email=robertomartinezp+matrule@gmail.com" -c commit.gpgsign=false commit -a'
alias analista='git -c "user.name=Ana Lista (User Persona)" -c "user.email=robertomartinezp+analista@gmail.com" -c commit.gpgsign=false commit -a'
alias presleyleads='git -c "user.name=Presley Leads (User Persona)" -c "user.email=robertomartinezp+presleyleads@gmail.com" -c commit.gpgsign=false commit -a'
alias victorstudior='git -c "user.name=Victor Stu Dior (User Persona)" -c "user.email=robertomartinezp+victorstudior@gmail.com" -c commit.gpgsign=false commit -a'
alias compiler='git -c "user.name=Susto Compiler (User Persona)" -c "user.email=robertomartinezp+compiler@gmail.com" -c commit.gpgsign=false commit -a'
